### ISSUE TITLE
[FEATURE] {{ dl-popup }} - {{ UI changes }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#356]
1. Change the padding-top to 16px
2. Close button- increase to 12px and align center with the title. 
3. Remove the margin from the title
4. Remove the padding top from the text. Remove the padding-bottom of the text (20px) and add instead a gap of 16px. Change the padding-right to 16px
5. Add a gap of 6 px between the title and text- default:6px. Make sure that the gap is customizable. 
6. 
![Screenshot 2023-06-01 at 9 55 36](https://github.com/dataloop-ai/components/assets/121247551/0ceea613-64fe-4ea8-a439-f61f59df559e)

**Comment by prodan-eric** [comment]
Solved points 1,2 and 3. The other ones are related to dl-textarea (as it is passed as a slot inside the popup for demo purpose, which essentially could have anything inside it). Since we're currently planning on rewriting dl-textarea and dl-input, those issues would be solved on that side instead of this.
