### ISSUE TITLE
[BUG] {{ dl select }} - {{ UI issues }}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#357]
**Disabled mode**

1. The tooltip is missing in disabled mode.
2. The chevron color should also be disabled (now it's medium). 

**dl select with chip**
1. There is no space between the chip and the chevron. A 6px space should be added between the two elements.
2. The chip size (outside the dropdown) should be similar to all chips. If a label is longer than the chip, add ... at the end of the label + a tooltip with the full name.
3. The chip menu: the label should be in the center.
![Screenshot 2023-06-01 at 10 12 04](https://github.com/dataloop-ai/components/assets/121247551/e8b4a93b-75ab-4406-964c-21dd59d285cd)
![Screenshot 2023-06-01 at 10 11 58](https://github.com/dataloop-ai/components/assets/121247551/d9853ec7-9cb6-468d-aec9-9bd4e361fae5)

**dl select with statuses**
1. The small dot next to the status name is missing - outside and inside the menu (see on Figma)
![Screenshot 2023-06-01 at 10 12 26](https://github.com/dataloop-ai/components/assets/121247551/64f706b7-e80a-4e5e-a598-429e0b777eca)

**dl select with label and sub-label**
1. Label color - dark (by default)
3. Sub-label color and font size- lighter and 10px (by default)
![Screenshot 2023-06-01 at 10 18 45](https://github.com/dataloop-ai/components/assets/121247551/3d3baa62-db50-4497-8dca-4e383f8dec0a)

**dl select with tooltip**
1. The title is missing.
2. Tooltip is missing
![Screenshot 2023-06-01 at 10 21 53](https://github.com/dataloop-ai/components/assets/121247551/d53c2022-597b-43f0-9bfa-6f8eee5bdd17)

**dl select a small size with a tooltip**
1. The info sign is not aligned with the title. ![Screenshot 2023-06-01 at 10 23 48](https://github.com/dataloop-ai/components/assets/121247551/631ff082-b614-47ab-a71f-1ca0b6ba823b)

**dl select small with scrolling**
1. The scroll is barely seen. Increase the scroll width by 2px (all places).

![Screenshot 2023-06-01 at 10 34 32](https://github.com/dataloop-ai/components/assets/121247551/3c48b2d7-8317-4312-b78a-91d74b475890)

**Comment by prodan-eric** [comment]
Disabled: 
1. Added disabledTooltip prop showing over the input itself when it's disabled
2. changed disabled chevron color
Select with chip: 
For these bugs please check the storybook as the issues seem to be site-specific @rotemshaham 

Label and SubLabel version:
the label and sublabel are fully customizable from outside with slots, I updated the demo
to replicate the case described

the title on the tooltip demo is missing because it wasn't specified in the demo(it was in other previews), not because the component doesn't support it

about the scrollbar width, this is inside dl-menu, not dl-select, but I made it possible to customize the menu's scrollbar width with a CSS variable and setting it to be 5px inside dl-select by default
