### ISSUE TITLE
[BUG] {{ dl table}} - {{ UI issues}}

### ISSUE THREAD

**Issue by rotemshaham** [dataloop-ai/components#364]
1. Resizing: Very difficult to resize columns. There are 2 lines (see the jumps), and one looks clickable but doesn't (the mouse cursor with pointer).
2. Remove from pagination the number of selected rows.
![Screenshot 2023-06-01 at 11 51 05](https://github.com/dataloop-ai/components/assets/121247551/42895946-ea01-4d44-a215-c0ac73dc77c7)

https://github.com/dataloop-ai/components/assets/121247551/0ca135b2-cc66-4773-a880-e6a62f080837

**Comment by VictorOpenTech** [comment]
@fadiDL, @rotemshaham, have discovered an old bug and would like to clarify if we need to fix it or the props we have built works properly for DL? Taking in consideration @vadim-popa-opentech is working for the Tree Table, he's in charge of the DL Table as well. This issue will be assign for him and latter on, let's say since Wednesday he could take a look at it if you'll come with confirmation of what exactly Vadim should fix 🙏
