### ISSUE TITLE
[BUG] DlSelect - when using emit-value and the option value is 0 it doesn't show as selected

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#427]
**To Reproduce**
```
options = [
                  {
                      label: '0',
                      value: 0
                  },
                  {
                      label: 'No',
                      value: 'no'
                  }
              ]
```
- Add "emit-value" prop to dl-select.
- Choose the option '0'

Current:
I see the placeholder and not the value '0' selected

Expected:
To see '0' selected.

**Comment by prodan-eric** [comment]
Not sure what this issue should be adressing exactly, but I fixed a bug where the Select didn't default on the first option if the emitValue prop was being set to true. Otherwise emitValue works as expected (if true, the Select will emit the option's value directly instead of the whole Option object on the @update:model-value event)

**Comment by fadiDL** [comment]
@prodan-eric thats exactly the bug. it did not work only for the first select option aka index 0.

also please check when you have an option that is defined like the following :
                  {
                      label: '0',
                      value: 0
                  },
                  
  that when having the emit-value prop it does infact emit this selected value meaning it emits a numeric 0 back.
  
  please add a test to this if you can aswell.
