### ISSUE TITLE
[BUG] DlSelect/DlMenu - fit-content and fit-container do not work

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#429]

**Comment by vadim-popa-opentech** [comment]
@advaa1234  please provide more information like where is the problem and what is the expected behavior

**Comment by fadiDL** [comment]
@vadim-popa-opentech We need to fix the components issue that when we use the DlSelect component the property the fit-content does not work. it stays with the fit-container option.
since we pass hardcoded fit-container and fit-content i believe it always behaves as fit-container. 

we need to remove the fit-container when fit-content is passed i believe.
test it out. add a test case and add a demo in the demo page please
