### ISSUE TITLE
[BUG] {{ DlTable }} - {{ Cant user regualr case on text }}

### ISSUE THREAD

**Issue by giladDataloop** [dataloop-ai/components#482]
**Describe the bug**
on DlTable - when using dl-tb - text content is always in title-case:

**Expected behavior**
Should have the option to set content to regular case

**Screenshots**
![image](https://github.com/dataloop-ai/components/assets/99115433/7c5c72d0-15f9-48a9-bae0-c63f88f17dcd)

**Device (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Comment by VictorOpenTech** [comment]
@fadiDL, could you make a list of components were should this changes aligned
Dl Transform Option is smthng new for us, we're not in charge of its implementation, but the issue seems pretty clear
@vadim-popa-opentech planning to fix all the issues related to the Tree Table till Wednesday and latter on he could take a look to the bug

**Comment by fadiDL** [comment]
@VictorOpenTech @vadim-popa-opentech the type `DlTransformOptions` is not new we use it in all of our components like 
- DlButton
- DlChip
- DlDropdownButton
- DlTypography

we would like that DlTd also have this styling behavior as a prop called `transform`
and by default it has the value `default` where that means we only capitalize the first letter of a text and not use `text-transform: capitalize`

**Comment by giladDataloop** [comment]
this one still occurs on 0.18.76
