### ISSUE TITLE
[BUG] DlSmartSearch - when using arrow keys to navigate suggestion and clicking enter it doesnt reset the caret position

### ISSUE THREAD

**Issue by fadiDL** [dataloop-ai/components#590]

**Comment by amzgrouplab** [comment]
To fix the issue where the caret position is not being reset when using arrow keys to navigate suggestion and clicking enter, you can try the following steps:

1. Check the code responsible for capturing the arrow key presses and click events. Ensure that the code is capturing both events correctly.

2. Check if the event's default behaviour is being prevented. If this is not being done, then the caret position might not reset automatically after pressing enter.

3. In the function that handles the click event or key press, ensure that the caret position is being reset when the user clicks on or navigates through the suggestions and hits enter.

4. You may also want to consider adding a separate function to reset the caret position whenever the user interacts with the input field, so that it always resets the caret position to the end of the input field.

5. Finally, test the updated function thoroughly to ensure that the caret position is being reset after pressing enter. Test with different input scenarios such as the type of text, the number of characters, different input methods (keyboard, mouse, touch), and edge cases.

I hope this helps you to resolve the issue. If you face any further issues or have any questions, please don't hesitate to ask.

**Comment by binary3oul** [comment]
So, if I understand correctly, after selecting a suggestion, the smart search input should regain focus, meaning that the text cursor should be placed back in the input field for further input. 
Is that what you're referring to?

**Comment by makc-dataloop** [comment]
@fadiDL 
> when using arrow keys to navigate suggestion and clicking enter it doesnt reset the caret position

seems to work for me:

https://github.com/dataloop-ai/components/assets/146977958/71a72329-a60e-4c2c-8a6e-3bdbe10f5462
