### ISSUE TITLE
[BUG] DlDatePicker - wrong endDate behavior

### ISSUE THREAD

**Issue by sefija** [dataloop-ai/components#655]
Date ranges need to start at the start of the "from" date and end at the end of the "to" date when not specifying time explicitly.

Currently, both dates use the start of the day except for when using the same date for both - handling for that use case was already added.

**Comment by makc-dataloop** [comment]
@fadiDL @sefija 
>  handling for that use case was already added

if I just enable that for all the dates, I get failed test:
<img width="811" alt="Screen Shot 2023-10-25 at 10 00 43 AM" src="https://github.com/dataloop-ai/components/assets/146977958/8e9602c1-a577-4c0b-a0cb-fe8d6af04ced">

so that did not work. Also, what does this part
> when not specifying time explicitly.

mean, exactly? unlike DlDateTimeRange, DlDatePicker does not seem to use DlTimePicker

**Comment by sefija** [comment]
@makc-dataloop I meant to say that the existing handling supports only the scenario where you are in multi-selection and you only choose one date - basically singular day selection.

Notice that the failing test you mentioned in your comment failed by quite a margin, the date was shifted by 10 years.

**Comment by makc-dataloop** [comment]
> Notice that the failing test you mentioned in your comment failed by quite a margin, the date was shifted by 10 years.

that was because the end-of-day date was calculated from "from" date instead of "to" date (there was no difference when they were equal, but now there is)
