### ISSUE TITLE
[BUG] {{ DlTable }} - {{ Scroll issue when adding new rows to the table }}

### ISSUE THREAD

**Issue by advaa1234** [dataloop-ai/components#725]
**Describe the bug**
We have a table that dynamically loads and inserts new rows as users scroll, activating the virtual scroll rendering. However, it appears that the insertion of new elements into the DOM causes the scroll position to shift upwards, occasionally making it difficult to access particular rows within the table.

https://github.com/dataloop-ai/components/assets/120374103/fe3c0bb0-8cf9-4fd8-bc8d-40d048e4fbd6

* Issue is reproducible using Vue2, haven't tested with Vue3.

**Comment by SorinOpt** [comment]
@advaa1234 can you provide please more details what specific we need to fix ? adding new elements inside table automatically will update scrollbar position, because table height overflow is updated based on new elements

**Comment by fadiDL** [comment]
@SorinOpt There are multiple issues here:
1. When new dynamic data is loaded we would like it so the table would not cause it to render a scroll animation instead stick in the same position. Meaning:
- When data is loaded the scroll bar shrinks
- Scroll bar does adjusts its position according to new data
- The table will not trigger a scroll as its already on that position

I understand why the scroll occurs as you described adding new data to the table would trigger the virtual scroll to recalculate the correct position of the scrollbar. is there a way to calculate that and jump to it if the scroll bar did not change instead of animating it and scrolling?

2. When using the virtual scroll with expandable-rows it will cause weird scroll behavior as i believe the row height changes dynamically causing weird scrolling if the expanded data is too long. 
Is there a way to change this behavior ? Having better calculation of row height ? we are experincing other issues with micro jumps in virtual scrolling i believe due to row-height not being assigned.

**Comment by SorinOpt** [comment]
So from what I understand, in the video the user doesn't scroll upwards at all, instead the virtual scroll jumps up after rendering the new elements? If that's the case then I don't know how to reproduce it inside the component demos, seems like very unexpected behaviour, especially as it's not even instant, but animated.
